[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

# Function configuration
[[plugins]]
  package = "@netlify/plugin-functions-install-core"

# Webhook function routing
[[redirects]]
  from = "/api/webhooks/clerk"
  to = "/.netlify/functions/clerk-webhook"
  status = 200

# Headers for webhook endpoint
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, svix-signature, svix-timestamp"

# Environment variables (set these in Netlify dashboard)
# CLERK_WEBHOOK_SECRET
# VITE_SUPABASE_URL  
# SUPABASE_SERVICE_ROLE_KEY
# VITE_CLERK_PUBLISHABLE_KEY 