name: CI

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      checks: write
      pull-requests: write

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        cache-dependency-path: package-lock.json

    - name: Install dependencies
      run: |
        cd web-app
        npm ci

    - name: Run tests
      run: |
        cd web-app
        npm run test:ci
      continue-on-error: true

    - name: Upload Jest coverage reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: jest-coverage-reports
        path: web-app/coverage/
        retention-days: 7
        if-no-files-found: warn

    - name: Publish Test Results
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: Jest Tests
        path: web-app/coverage/junit.xml
        reporter: jest-junit
        fail-on-error: false

    - name: Generate Coverage Badge
      uses: action-badges/cobertura-coverage-xml-badges@0.2.1
      if: success()
      with:
        file-name: coverage.svg
        badge-branch: badges
        github-token: '${{ secrets.GITHUB_TOKEN }}'
        coverage-file-name: web-app/coverage/cobertura-coverage.xml

  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        cache-dependency-path: package-lock.json

    - name: Install dependencies
      run: |
        cd web-app
        npm ci

    - name: Build
      run: |
        cd web-app
        npm run build

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: web-app/dist/
        retention-days: 1

  security:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        cache-dependency-path: package-lock.json

    - name: Install dependencies
      run: |
        cd web-app
        npm ci

    - name: Audit dependencies
      run: |
        cd web-app
        npm audit --audit-level=high

  e2e-visual:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
      checks: write
      pull-requests: write

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        cache-dependency-path: package-lock.json

    - name: Install dependencies
      run: |
        cd web-app
        npm ci

    - name: Install Playwright Browsers
      run: |
        cd web-app
        npx playwright install --with-deps

    - name: Run Playwright visual tests (Chromium only)
      env:
        CI: true
      run: |
        cd web-app
        npx playwright test --config ../.config/playwright/playwright.config.js --project=chromium

    - name: Upload Playwright HTML report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: playwright-html-report
        path: web-app/playwright-report/
        retention-days: 7
        if-no-files-found: warn

    - name: Upload Playwright results (JSON/JUnit/traces)
      if: success() || failure()
      uses: actions/upload-artifact@v4
      with:
        name: playwright-test-results
        path: |
          web-app/test-results/
        retention-days: 7
        if-no-files-found: warn

    - name: Publish Playwright JUnit Results
      if: success() || failure()
      uses: dorny/test-reporter@v1
      with:
        name: Playwright E2E (Chromium)
        path: web-app/test-results/results.xml
        reporter: java-junit
        fail-on-error: false